name: teno_textsearch
description: A super simple full text search that supports export/import indexes.
version: 0.0.3
repository: https://github.com/hnvcam/teno_textsearch

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
